### Get all members (gateway)

GET http://localhost:8084/api/members

### Get all guilds (gateway)

GET http://localhost:8084/api/guilds

### Get all members (member)

GET http://localhost:8082/api/members

### Get all guilds (guild)

GET http://localhost:8081/api/guilds

### Delete guild

DELETE http://localhost:8081/api/guilds/89776d34-c8f5-47cf-b6d5-8be8ecc548d2

### Delete member

DELETE http://localhost:8082/api/members/881856a2-02fa-4775-b2f6-951e7ca19308