### Get all members (gateway)

GET http://localhost:8084/api/members

### Get all guilds (gateway)

GET http://localhost:8084/api/guilds

### Get member

GET http://localhost:8082/api/members/c47f02c3-2ad0-409f-9999-abce2c506bd2